pull_request_rules:
  - name: Automatic merge
    conditions:
      - "#approved-reviews-by>=1"
      - label=automerge
      - status-success=Travis CI - Pull Request
    actions:
      merge:
        method: merge
